//GLSL version to use
#version 460

//size of a workgroup for compute
layout (local_size_x = 16, local_size_y = 16) in;

//descriptor bindings for the pipeline
layout(rgba16f,set = 0, binding = 0) uniform image2D image;


void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);

    int color_val = texelCoord.x % 2 == 0 ? 1 : 0;
    vec4 color = vec4(color_val, color_val, color_val, 1);

    imageStore(image, texelCoord, color);
}